### ISSUE TITLE
System.ObjectDisposedException when ConfirmSubscriptionAsync() is not called

### ISSUE THREAD

**Issue by ignas-sakalauskas-cko** [ignas-sakalauskas/SnsTestReceiver#5]
SDK throws `System.ObjectDisposedException` when ConfirmSubscriptionAsync() is not called. Stacktrace below.

```
 Error Message:
   System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'DefaultMeterFactory'.
  Stack Trace:
     at Microsoft.Extensions.Diagnostics.Metrics.DefaultMeterFactory.Create(MeterOptions options)
   at System.Net.Http.Metrics.MetricsHandler..ctor(HttpMessageHandler innerHandler, IMeterFactory meterFactory, Meter& meter)
   at System.Net.Http.SocketsHttpHandler.SetupHandlerChain()
   at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SnsTestReceiver.Sdk.SnsTestReceiverClient.InternalSearchAsync(String text, Nullable`1 limit)
   at SnsTestReceiver.Sdk.SnsTestReceiverClient.SearchAsync(String text, Nullable`1 limit)
```

This only happens when a base class is used to setup integration tests.

**Comment by ignas-sakalauskas** [comment]
This issue happens due to incorrect HttpClient lifecycle management. I exposed `IHttpClientBuilder` just in case someone wanted to override HttpClient settings.
